# Generated by Django 3.2.2 on 2021-05-17 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20210514_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlist',
            name='current_largest_bid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=1000, null=True),
        ),
    ]
